name: Build dumb PyPI on GH pages

on:
  push:
  pull_request:
  schedule:
  # https://crontab.guru/#23_*/4_*_*_*
  - cron: 23 */4 * * *  # At minute 23 past every 4th hour.

jobs:
  build-dumb-pypi:
    name: Build nightlies
    runs-on: ubuntu-latest

    steps:
    - name: Check out ansible-community/ansible-build-data src from Git
      uses: actions/checkout@v2
      with:
        path: ansible-build-data
        ref: main
        repository: ansible-community/ansible-build-data
    - name: Switch to Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Make 'dist/' dir
      run: |
        from pathlib import Path
        Path('dist').mkdir()
      shell: python
    - name: Install packaging-related dists from PyPI
      run: >-
        python -m
        pip install
        -U --user
        pip setuptools wheel
    - name: Install antsibull dist from PyPI
      run: python -m pip install -U --user antsibull
    - name: Install antsibull dist from GitHub
      run: >-
        python -m
        pip install
        -U --user
        git+https://github.com/ansible-community/antsibull.git
    - name: Generate the list of compatible versions
      run: >-
        ~/.local/bin/antsibull-build
        new-ansible 2.10.0
        --data-dir ansible-build-data/2.10
    - name: Create a single-tarball Ansible dist
      run: >-
        ~/.local/bin/antsibull-build
        single 2.10.0
        --data-dir ansible-build-data/2.10
        --sdist-dir dist
    - name: Check out ansible/ansible@devel src from Git
      uses: actions/checkout@v2
      with:
        path: ansible--ansible--devel
        ref: devel
        repository: ansible/ansible
    - name: Install packaging-related dists from PyPI
      run: >-
        python -m
        pip install
        -U --user
        packaging straight.plugin
    - name: Build ansible/ansible@devel
      env:
        _ANSIBLE_SDIST_FROM_MAKEFILE: 1
      run: |
        make sdist_check
        python -m setup sdist --dist-dir=../dist
      working-directory: ansible--ansible--devel
    - name: Make ansible version stable
      run: >-
        sed -i
        "s/^\(__version__ = '\)\([0-9]\+.[0-9]\+.[0-9]\+\)\.\(dev\|a\|b\|rc\)[0-9]\+\('\)$/\1\2\4/g"
        lib/ansible/release.py
      working-directory: ansible--ansible--devel
    - name: Build ansible/ansible@devel as stable
      env:
        _ANSIBLE_SDIST_FROM_MAKEFILE: 1
      run: |
        make sdist_check
        python -m setup sdist --dist-dir=../dist
      working-directory: ansible--ansible--devel
    - name: Install dumb-pypi dist from PyPI
      run: python -m pip install dumb-pypi --user
    - name: Generate a dumb PyPI website
      run: |
        python -m dumb_pypi.main \
          --package-list <(ls dist) \
          --packages-url https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/dist \
          --output-dir gh-pages-dumb-pypi
      shell: bash
    - name: Copy dists over to the generated dumb PyPI website dir
      run: cp -av dist gh-pages-dumb-pypi/
    - name: Publish the dumb PyPI website to GH Pages
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages-dumb-pypi
