name: Build dumb PyPI on GH pages

on:
  push:
  pull_request:
  schedule:
  # https://crontab.guru/#23_*/4_*_*_*
  - cron: 23 */4 * * *  # At minute 23 past every 4th hour.

jobs:
  build-dumb-pypi:
    name: Build nightlies
    runs-on: ubuntu-latest

    steps:
    - name: Check out ansible/ansible@devel src from Git
      uses: actions/checkout@v2
      with:
        path: ansible--ansible--devel
        ref: devel
        repository: ansible/ansible
    - name: Install packaging-related dists from PyPI
      run: python -m pip install -U packaging setuptools pip wheel straight.plugin
    - name: Build ansible/ansible@devel
      run: make snapshot
      working-directory: ansible--ansible--devel
    - name: Install dumb-pypi dist from PyPI
      run: python -m pip install dumb-pypi --user
    - name: Generate a dumb PyPI website
      run: |
        python -m dumb_pypi.main \
          --package-list <(ls ansible--ansible--devel/dist) \
          --packages-url ./dist \
          --output-dir gh-pages-dumb-pypi
      shell: bash
    - name: Copy dists over to the generated dumb PyPI website dir
      run: cp -av ansible--ansible--devel/dist gh-pages-dumb-pypi/
    - name: Publish the dumb PyPI website to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        force_orphan: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages-dumb-pypi
